CREATE TABLE IF NOT EXISTS `civicrm_dsa_compose` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `case_id` int(11) NOT NULL,
  `activity_id` int(11) NOT NULL COMMENT 'this table contains additional data for activities of type DSA',
  `pid` int(11) DEFAULT NULL COMMENT 'parent is for dsa creditation',
  `cid` int(11) NOT NULL COMMENT 'contact id',
  `loc_id` int(11) DEFAULT NULL COMMENT 'location id',
  `percentage` int(3) DEFAULT NULL,
  `days` int(3) DEFAULT NULL,
  `amount_dsa` decimal(7,2) DEFAULT NULL,
  `amount_briefing` decimal(7,2) DEFAULT NULL,
  `amount_debriefing` decimal(7,2) DEFAULT NULL,
  `amount_airport` decimal(7,2) DEFAULT NULL,
  `amount_transfer` decimal(7,2) DEFAULT NULL,
  `amount_hotel` decimal(7,2) DEFAULT NULL,
  `amount_visa` decimal(7,2) DEFAULT NULL,
  `amount_outfit` decimal(7,2) DEFAULT NULL,
  `amount_other` decimal(7,2) DEFAULT NULL,
  `description_other` text COLLATE utf8_unicode_ci,
  `amount_advance` decimal(7,2) DEFAULT NULL,
  `approval_cid` int(11) DEFAULT NULL COMMENT 'approver contact id',
  `approval_datetime` datetime DEFAULT NULL,
  `payment_id` int(11) DEFAULT NULL COMMENT 'payment line id',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1;
